Comunicatii java to py
code4romania/czl-scrape pull request #86
Opened 2017-04-25 08:43 UTC by rares-urdea

Varianta functionala care nu trimite inca nimic la API.
Lipseste data de publicare. Pe foarte multe articole nu este mentionata, iar structura inexistenta face lucrurile cu atat mai complicate.
Lipseste logging-ul si optiunile de run.

2017-04-25 09:22 UTC, mgax commented on scrapy/czlscrape/spiders/comunicatii.py
> +from datetime import *
PEP8 (the Python style guide) [zice](https://www.python.org/dev/peps/pep-0008/#imports) să evităm `import *` pentru că nu mai e clar de unde e importat fiecare simbol.

2017-04-25 09:22 UTC, mgax commented on scrapy/czlscrape/spiders/comunicatii.py
> +WRAPPER_XPATH = '//div/div[3]/div/div/div[2]/div/div/div/div/div'
La prima vedere, pare un selector fragil, n-ai putea să te folosești de clase CSS? De exemplu ca [aici](https://github.com/code4romania/czl-scrape/blob/master/justitie/just/spiders/publications.py#L29).

2017-04-25 09:22 UTC, mgax commented on scrapy/czlscrape/spiders/comunicatii.py
> +    @staticmethod
Ai putea să scoți funcțiile astea în afara clasei, mai reduci din sintaxă boilerplate.

2017-04-25 09:22 UTC, mgax commented on scrapy/czlscrape/spiders/comunicatii.py
> +                    print('Warning: null current_item or no title. Found documents')
Ai putea să folosești modulul `logging` pentru warning-uri. Astfel, vor fi trimise către [Sentry](https://logs.code4.ro). Ceva de genul [ăsta](https://github.com/code4romania/czl-scrape/blob/master/scrapy/czlscrape/pipelines.py#L51).

2017-04-25 09:22 UTC, mgax commented on scrapy/czlscrape/spiders/dialog.py
> -
Dacă vrei să schimbi coding style, propun să faci un PR separat, eu personal prefer indentarea așa cum era :)

2017-04-25 09:22 UTC, mgax commented on scrapy/czlscrape/utils.py
> +    for substr, publication_type in rules:
Crezi că o să difere regulile pentru fiecare spider? Mă aștept să avem cam aceleași reguli pentru toate site-urile.

2017-04-25 10:54 UTC, xlotlu commented on scrapy/czlscrape/utils.py
> +    for substr, publication_type in rules:
Parțial off-topic și nu prea: spiderele nu ar trebui să se ocupe de logica asta. Guessing-ul să se facă la receiver, unificat.
Spiderele pot în schimb să trimită `type` atunci când îl știu cu siguranță din ce-au scrapat.

[romgleză cu diacritice. for the win.]

2017-04-25 19:55 UTC, rares-urdea commented on scrapy/czlscrape/spiders/comunicatii.py
> +WRAPPER_XPATH = '//div/div[3]/div/div/div[2]/div/div/div/div/div'
Din pacate, nu are niciun fel de structura site-ul de la comunicatii. Totusi, daca ai vreo idee de unde selector mai stabil, n-am nimic impotriva sa schimbam.

2017-04-25 20:00 UTC, rares-urdea commented on scrapy/czlscrape/spiders/comunicatii.py
> +                    print('Warning: null current_item or no title. Found documents')
Yeah, work in progress. N-am bagat logging deloc, inca.

2017-04-25 20:01 UTC, rares-urdea commented on scrapy/czlscrape/spiders/dialog.py
> -
Nu a fost intentionat. Probabil am dat format si pe dialog, din greseala.

2017-04-25 20:08 UTC, rares-urdea commented on scrapy/czlscrape/utils.py
> +    for substr, publication_type in rules:
Da, spre exemplu intre dialog si comunicatii difera. Poate ca sunt si alte situatii, n-am verificat. Legat de guessing la receiver - in comunicatii am nevoie de type ca identific titlurile si sa separ articolele, nefiind absolut nicio structura. Daca scoatem logica asta din spider, nu mai pot separa articolele.

2017-04-25 20:08 UTC, rares-urdea commented on scrapy/czlscrape/spiders/comunicatii.py
> +    @staticmethod
Sure, will do.

2017-04-25 20:10 UTC, xlotlu commented
Ce-nseamna sa separi articole?

On 04/25/2017 11:08 PM, Rares Urdea wrote:
> *@rares-urdea* commented on this pull request.
>
> ------------------------------------------------------------------------
>
> In scrapy/czlscrape/utils.py
> <https://github.com/code4romania/czl-scrape/pull/86#discussion_r113297137>:
>
>> @@ -0,0 +1,15 @@
> +import re
> +
> +
> +def guess_publication_type(text, rules):
> +    text = text.lower()
> +    text = re.sub(r'[șş]', 's', text)
> +    text = re.sub(r'[țţ]', 't', text)
> +    text = re.sub(r'[ăâ]', 'a', text)
> +    text = re.sub(r'[î]', 'i', text)
> +
> +    for substr, publication_type in rules:
>
> Da, spre exemplu intre dialog si comunicatii difera. Poate ca sunt si
> alte situatii, n-am verificat. Legat de guessing la receiver - in
> comunicatii am nevoie de type ca identific titlurile si sa separ
> articolele, nefiind absolut nicio structura. Daca scoatem logica asta
> din spider, nu mai pot separa articolele.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/code4romania/czl-scrape/pull/86#discussion_r113297137>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAITodVKiQs6JLTgNVco3ZxQJcuAte4fks5rzlLAgaJpZM4NHK5L>.
>

2017-04-25 20:11 UTC, rares-urdea commented on scrapy/czlscrape/spiders/comunicatii.py
> +from datetime import *
👍

2017-04-25 20:11 UTC, xlotlu commented on scrapy/czlscrape/utils.py
> +    for substr, publication_type in rules:
Ce-nseamna sa separi articole?

2017-04-25 20:14 UTC, rares-urdea commented on scrapy/czlscrape/utils.py
> +    for substr, publication_type in rules:
Pe site-ul de la comunicatii, fiecare bucata de informatie este aruncata intr-un <p> tag. Nu exista niciun fel de structura care sa indice unde incepe si unde se termina un anumit articol (proiect de lege, hotarare, ordin, etc).

2017-04-25 20:15 UTC, xlotlu commented on scrapy/czlscrape/utils.py
> +    for substr, publication_type in rules:
am inteles. that sounds lovely.

2017-04-26 08:41 UTC, mgax commented on scrapy/czlscrape/spiders/comunicatii.py
> +WRAPPER_XPATH = '//div/div[3]/div/div/div[2]/div/div/div/div/div'
Poate să te folosești de clasa `.wpb_text_column`?

2017-04-26 08:48 UTC, margelatu commented on scrapy/czlscrape/utils.py
> +    for substr, publication_type in rules:
Si totusi cred ca regulile de detectie a tipului unui proiect legislativ nu difera. Poate pentru comunicatii regulile sunt mai stufoase, iar pentru dialog sunt mai simple. Chiar si asa, ma astept ca o singura bucata de cod sa le acopere pe toate. Va scriu asta si cu celelalte scrapere in mind unde am vazut logica similara sau chiar identica.

2017-04-26 08:53 UTC, margelatu commented on scrapy/czlscrape/utils.py
> +    for substr, publication_type in rules:
De exemplu: la cultura sunt mai multe scenarii, dar codul e similar. Diferenta ar fi ca acolo e nevoie de regex-uri, ceea ce as recomanda si aici.

2017-04-27 14:42 UTC, rares-urdea commented on scrapy/czlscrape/utils.py
> +    for substr, publication_type in rules:
@margelatu De acord, o singura bucata de cod le poate acoperi pe toate. Pentru asta am scos functia respectiva in utils. Daca e nevoie de reguli speciale, se pot folosi. Daca nu, putem folosi o singura regula pentru oricate spidere.

2017-05-15 08:31 UTC, margelatu requested changes
Scraperul arata bine si se executa corect. O singura observatie, numele scraperului ar trebui sa fie "comunicatii"

2017-05-15 08:31 UTC, margelatu commented on scrapy/czlscrape/spiders/comunicatii.py
> +    name = "quotes"
This should be "comunicatii" :-)

2017-05-15 11:38 UTC, merged